name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Build Docker image
      if: github.ref == 'refs/heads/master'
      run: |
        export MVN_VERSION=$(mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec)
        docker build -t docker.pkg.github.com/nicko/simple-organiser/simple-organiser:$MVN_VERSION .
    - name: Push to github packages
      if: github.ref == 'refs/heads/master'
      env:
        DOCKER_USERNAME: nicko
        DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      run: |
        export MVN_VERSION=$(mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec)
        echo $DOCKER_PASSWORD | docker login docker.pkg.github.com -u DOCKER_USERNAME --password-stdin
        docker push docker.pkg.github.com/nicko/simple-organiser/simple-organiser:$MVN_VERSION
